### ISSUE TITLE
How to retrive latlng when user in auto trip ?

### ISSUE THREAD

**Issue by rajasekaranm** [DriveQuantPublic/android-sample-app#1]
HI,
I have using this sdk for trip recording but I unable get the user position when user in auto trip.

So kindly let me know solution for it

**Comment by DriveQuantPublic** [comment]
@rajasekaranm Hi, please send us an email to developer@drivequant.com with the API Key we sent you so we can check if we have recorded some trips on our backoffice

Kind regards,

DriveQuant Android Team
